# Generated by Django 2.2.2 on 2019-06-15 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('maxPlayers', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(50)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Clan')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='clanMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.User'),
        ),
    ]
