# Generated by Django 2.2.1 on 2019-06-27 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='ally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.UserSnapshot', verbose_name='Alleato'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='allyDestruction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Danni inflitti'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='allyVictory',
            field=models.BooleanField(default=False, verbose_name='Vittoria'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.UserSnapshot', verbose_name='Nemico'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='enemyDestruction',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Danni subiti'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='maxMembers',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Numero massimo di membri'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
