# Generated by Django 2.2.1 on 2019-06-15 17:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.Clan'),
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allyDestruction', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enemyDestruction', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('allyVictory', models.BooleanField()),
                ('ally', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manager.User')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.User')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='manager.War')),
            ],
        ),
    ]
