# Generated by Django 2.2.1 on 2019-06-20 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='ally',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battle',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='manager.EnemyUserSnapshot'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='manager.War'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clanMaster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enemyusersnapshot',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='manager.War'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='manager.Clan'),
        ),
        migrations.AlterField(
            model_name='war',
            name='allyClan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wars', to='manager.Clan'),
        ),
    ]
