# Generated by Django 2.2.1 on 2019-06-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190620_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clan',
            old_name='maxPlayers',
            new_name='maxMembers',
        ),
    ]
