# Generated by Django 2.2.2 on 2019-06-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20190620_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='allyVictory',
            field=models.BooleanField(default=False),
        ),
    ]
